In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
# Define vocab size
voc_size=10000

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3283, 4605, 8837, 3939],
 [3283, 4605, 8837, 4945],
 [3283, 3611, 8837, 5712],
 [5579, 5921, 6836, 1782, 1786],
 [5579, 5921, 6836, 1782, 9838],
 [509, 3283, 1792, 8837, 7898],
 [7155, 3705, 5918, 1782]]

In [ ]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences # So that all the sentences are of equal length
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3283 4605 8837 3939]
 [   0    0    0    0 3283 4605 8837 4945]
 [   0    0    0    0 3283 3611 8837 5712]
 [   0    0    0 5579 5921 6836 1782 1786]
 [   0    0    0 5579 5921 6836 1782 9838]
 [   0    0    0  509 3283 1792 8837 7898]
 [   0    0    0    0 7155 3705 5918 1782]]


In [14]:
# Feature Representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 172ms/step


array([[[ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
         -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
          3.5526816e-02, -1.7165113e-02],
        [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
         -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
          3.5526816e-02, -1.7165113e-02],
        [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
         -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
          3.5526816e-02, -1.7165113e-02],
        [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
         -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
          3.5526816e-02, -1.7165113e-02],
        [ 6.9070086e-03, -8.9436658e-03, -9.2847124e-03,  2.6714001e-02,
         -3.0903174e-02, -3.8811624e-02,  4.1129161e-02,  3.1833593e-02,
         -4.9145222e-02, -2.7726650e-02],
        [ 4.2246927e-02,  1.9720245e-02, -1.7557312e-02,  1.

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3283, 4605, 8837, 3939])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 63ms/step


array([[ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
        -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
         3.5526816e-02, -1.7165113e-02],
       [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
        -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
         3.5526816e-02, -1.7165113e-02],
       [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
        -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
         3.5526816e-02, -1.7165113e-02],
       [ 4.4136714e-02, -2.9039228e-02, -1.3596810e-02,  3.5203043e-02,
        -9.7123757e-03,  3.7707422e-02,  4.7549639e-02,  2.3239043e-02,
         3.5526816e-02, -1.7165113e-02],
       [ 6.9070086e-03, -8.9436658e-03, -9.2847124e-03,  2.6714001e-02,
        -3.0903174e-02, -3.8811624e-02,  4.1129161e-02,  3.1833593e-02,
        -4.9145222e-02, -2.7726650e-02],
       [ 4.2246927e-02,  1.9720245e-02, -1.7557312e-02,  1.4472753e-05,
   